spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/edustor_accounts
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
  data:
    mongodb:
      database: edustor-accounts
edustor:
  accounts:
    registration: false